version: "3.9"
services:
    web:
        build: ./frontend/
        ports:
            - "3000:3000"
    java:
        build: ./backend/apartment-viewing-booking/
        ports:
            - "8080:8080"
